math_phrase_to_symbol = {
    "area": "A",
    "volume": "V",
    "perimeter": "P",
    "radius": "r",
    "diameter": "d",
    "circumference": "C",
    "height": "h",
    "width": "w",
    "length": "l",
    "base": "b",
    "slope": "m",
    "intercept": "b",
    "slope-intercept form": "y = mx + b",
    "point-slope form": "y - y1 = m(x - x1)",
    "standard form": "Ax + By = C",
    "vertex form": "y = a(x - h)² + k",
    "factored form": "y = a(x - r1)(x - r2)",
    "quadratic formula": "x = (-b ± sqrt(b² - 4ac)) / (2a)",
    "discriminant": "D = b² - 4ac",
    "vertex": "(h, k)",
    "focus": "(h, k + p/4a)",
    "directrix": "y = k - p/4a",
    "asymptote": "y = mx + b",
    "hyperbola": "x²/a² - y²/b² = 1",
    "ellipse": "x²/a² + y²/b² = 1",
    "parabola": "y = ax² + bx + c",
    # Add more as needed
} 