physics_phrase_to_symbol = {
    "force": "F",
    "mass": "m",
    "acceleration": "a",
    "velocity": "v",
    "initial velocity": "u",
    "final velocity": "v",
    "momentum": "p",
    "work": "W",
    "power": "P",
    "energy": "E",
    "distance": "s",
    "time": "t",
    "gravitational constant": "G",
    "gravitational force": "Fg",
    "gravitational potential energy": "Ug",
    "gravitational potential": "Vg",
    "gravitational field strength": "g",
    "gravitational field": "E",
    "potential energy": "U",
    "kinetic energy": "K",
    "elastic potential energy": "Ue",
    "elastic potential": "Ve",
    "elastic force": "Fe",
    "elastic constant": "k",
    "elastic modulus": "E",
    "height": "h",
    "one half": "1/2",
    "one third": "1/3",
    "two thirds": "2/3",
    "four thirds": "4/3",
    # Add more as needed
} 